namespace FINCORE.Models.Models.Acquisition.BPKB
{
    public class BPKBCMModel
    {
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public string CreditId { get; set; }
        public DateTime? CreditDate { get; set; }
        public string FinCode { get; set; }
        public byte? IsQq { get; set; }
        public string QqName { get; set; }
        public string DealerCode { get; set; }
        public byte? Tenor { get; set; }
        public string AccountReceiveable { get; set; }
        public string InstallmentId { get; set; }
        public decimal? AssetCost { get; set; }
        public decimal? GrossDownPayment { get; set; }
        public decimal? DiscDeposit { get; set; }
        public decimal? Deposit { get; set; }
        public decimal? AmountInstallment { get; set; }
        public decimal? AdminFee { get; set; }
        public decimal? InsuranceFee { get; set; }
        public decimal? NettDownPayment { get; set; }
        public decimal? JmlPembiayaan { get; set; }
        public decimal? RateValue { get; set; }
        public decimal? EffectiveRate { get; set; }
        public decimal? FlatRate { get; set; }
        public decimal? OverdueRate { get; set; }
        public string ItemId { get; set; }
        public string ItemMerkId { get; set; }
        public string ItemMerkTypeId { get; set; }
        public string YearItem { get; set; }
        public int? ProductId { get; set; }
        public DateTime? FinishDate { get; set; }
        public string StatusApproval { get; set; }
        public string DiscType { get; set; }
        public decimal? OngkosTagih { get; set; }
        public decimal? OngkosBbn { get; set; }
        public byte? IsItemNew { get; set; }
        public string ChannelName { get; set; }
        public string StatusCm { get; set; }
        public string IsTutupBuka { get; set; }
        public string ApprovalDescription { get; set; }
        public string ApplicationTypeId { get; set; }
        public DateTime? ReasonRfa { get; set; }
        public bool? CollectiblePeriod { get; set; }
        public string CollectibleSequencePeriod { get; set; }
        public string Op { get; set; }
        public string Uli { get; set; }
        public decimal? Lcr { get; set; }
        public decimal? FirstOp { get; set; }
        public decimal? FirstUli { get; set; }
        public decimal? FirstLcr { get; set; }
        public decimal? ApprovedBy { get; set; }
        public string ApprovedDate { get; set; }
        public string IsConvert { get; set; }
        public string LastPayDate { get; set; }
        public string AreaCollectionKonsId { get; set; }
        public bool? IsMilikPt { get; set; }
        public string PoSource { get; set; }
        public string PoSourceOther { get; set; }
        public string NikCollectionCode { get; set; }
        public string NikSurveryorCode { get; set; }
        public string ChannelId { get; set; }
        public string ProductMarketingId { get; set; }
        public string UsrCorrection { get; set; }
        public string DtmCorrection { get; set; }
        public DateTime? IsFlagQuota { get; set; }
        public string PackageId { get; set; }
        public bool? ProgramId { get; set; }
        public string InsuranceFeeGross { get; set; }
        public string UangMukaMurniKons { get; set; }
        public decimal? InstallmentDecimal { get; set; }
        public string ModelId { get; set; }
        public string Cc { get; set; }
        public decimal? FirstPayment { get; set; }
        public string TipeGuna { get; set; }
        public string IsNewPriceList { get; set; }
        public int? BiayaProvisi { get; set; }
        public string BiayaProvisiIns { get; set; }
        public string NikMh { get; set; }
        public string TipeCover { get; set; }
        public string BiayaProsesId { get; set; }
        public string NominalBiayaProses { get; set; }
        public bool? PackagePembiayaanSecq { get; set; }
        public string PaketPembiayaanId { get; set; }
        public string BiayaProsesSecq { get; set; }
        public string IsTac { get; set; }
        public string TacMax { get; set; }
        public string KomperMax { get; set; }
        public bool? LeasingCode { get; set; }
        public decimal? RefundBunga { get; set; }
        public decimal? RefundBungaPercent { get; set; }
        public string InsuranceTypeId { get; set; }
        public string InterestRateTypeId { get; set; }
    }
}