namespace FINCORE.Models.Models.Acquisition.Reports
{
    public class PrintLAHSModels
    {
        public decimal MobileSurveyID { get; set; }
        public string NamaPemohon { get; set; }
        public string AlamatPemohon { get; set; }
        public string NoTelepon { get; set; }
        public string SumberDana { get; set; }
        public string HubunganDenganPemohon { get; set; }
        public string JenisPekerjaan { get; set; }
        public string StatusTempatTinggal { get; set; }
        public string BuktiKepemilikanRumah { get; set; }
        public string NamaPadaBuktiKepemilikan { get; set; }
        public string HubunganBuktiKepemilikanRumah { get; set; }
        public string LamaMenempatiRumah { get; set; }
        public string KondisiRumah { get; set; }
        public string LokasiRumah { get; set; }
        public string DayaListrik { get; set; }
        public string PembayaranListrik { get; set; }
        public string LuasTanah { get; set; }
        public string StatusKaryawan { get; set; }
        public string LamaBekerja { get; set; }
        public string Jabatan { get; set; }
        public string Posisi { get; set; }
        public string NamaInstansi { get; set; }
        public string NoTeleponTempatKerja { get; set; }
        public string JenisInstansi { get; set; }
        public string SkalaPerusahaan { get; set; }
        public string BidangUsaha { get; set; }
        public string JenisUsaha { get; set; }
        public string DetailJenisUsaha { get; set; }
        public string JenisKomoditi { get; set; }
        public string JumlahKaryawanDiTempatKerja { get; set; }
        public string LamaBerdiriInstansi { get; set; }
        public string LokasiInstansi { get; set; }
        public string PekerjaanPasangan { get; set; }
        public string PenghasilanTambahan { get; set; }
        public string WiraswastaNamaInstansi { get; set; }
        public string WiraswastaJenisUsaha { get; set; }
        public string WiraswastaDetailJenisUsaha { get; set; }
        public string WiraswastaJenisKomoditi { get; set; }
        public string WiraswastaLamaUsaha { get; set; }
        public string WiraswastaSkalaUsaha { get; set; }
        public string WiraswastaFisikUsaha { get; set; }
        public string WiraswastaLokasiUsaha { get; set; }
        public string WiraswastaTempatUsaha { get; set; }
        public string WiraswastaKepemilikanUsaha { get; set; }
        public string WiraswastaModalUsaha { get; set; }
        public string WiraswastaKebutuhanAkanKomoditi { get; set; }
        public string WiraswastaTingkatKompetisi { get; set; }
        public string WiraswastaJumlahKaryawan { get; set; }
        public string WiraswastaAktivitasTransaksiUsaha { get; set; }
        public string WiraswastaKeahlianKhususUntukMenjalankanUsahaTersebut { get; set; }
        public string WiraswastaPekerjaanPasangan { get; set; }
        public string ApakahPernahMengajukanKreditSebelumnya { get; set; }
        public string TujuanPenggunaanUnit { get; set; }
        public string SiapaPenggunaUnitModal { get; set; }
        public string FrekuensiPenggunaanUnit { get; set; }
        public string RataRataJarakPemakaianUnit { get; set; }
        public string JumlahTanggungan { get; set; }
        public string AnggotaKeluargaUsiaLebihDari15Tahun { get; set; }
        public string JumlahKendaraanYangDimiliki { get; set; }
        public string TujuanPenggunaanModal { get; set; }
        public decimal PendapatanUtama { get; set; }
        public decimal PendapatanPasangan { get; set; }
        public decimal PendapatanTambahan1 { get; set; }
        public decimal PendapatanTambahan2 { get; set; }
        public decimal TotalPendapatan { get; set; }
        public decimal BiayaRumahTangga { get; set; }
        public decimal BiayaListrikAir { get; set; }
        public decimal BiayaPendidikan { get; set; }
        public decimal BiayaPulsaTelepon { get; set; }
        public decimal CicilanLainnya { get; set; }
        public decimal TotalPengeluaran { get; set; }
        public string KualitasSumberOrder { get; set; }
        public string NasabahSulitDitemui { get; set; }
        public string TidakKooperatif { get; set; }
        public string PindahAlamat { get; set; }
        public string AtasNama { get; set; }
        public string NasabahFiktif { get; set; }
        public string UnitDigadai { get; set; }
        public string CampurTanganPihakKetiga { get; set; }
        public string KapasitasMenurun { get; set; }
        public string PenghasilanMenurun { get; set; }
        public string PindahKerja { get; set; }
        public string KtpNasabah { get; set; }
        public string KtpPasanganPenjamin { get; set; }
        public string KartuKeluarga { get; set; }
        public string ValidasiBuktiKepemilikanRumah { get; set; }
        public string BuktiPenghasilan { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public decimal MobileCASID { get; set; }
        public decimal MobileFCLID { get; set; }
        public decimal MobileSurveyIDs { get; set; }
        public string TipeAplikasi { get; set; }
        public string TipeFinance { get; set; }
        public string TipeBaruBekas { get; set; }
        public string NamaDealer { get; set; }
        public string Merk { get; set; }
        public string Type { get; set; }
        public decimal HargaKendaraan { get; set; }
        public decimal UangMuka { get; set; }
        public string JenisTenor { get; set; }
        public int Tenor { get; set; }
        public decimal NominalAngsuran { get; set; }
        public string Statuscasmobile { get; set; }
        public string AssetSeriesID { get; set; }
        public string FreshOrder { get; set; }
        public string TekananApproval { get; set; }
        public string KonflikKepentingan { get; set; }
        public string AlurProses { get; set; }
        public string ProfilNasabah { get; set; }
        public string ProfilkebutuhanUnit { get; set; }
        public string ProfilKemampuanBayar { get; set; }
        public string KesimpulanAnalisa { get; set; }
        public string CAKelengkapanLAHS { get; set; }
        public string CAKualitasSumberOrder { get; set; }
        public string CAKonflikKepentingan { get; set; }
        public string CAAlurProses { get; set; }
        public string CAProfilNasabah { get; set; }
        public string CAProfilKebutuhanUnit { get; set; }
        public string CAProfilKelancaranBayar { get; set; }
        public string CAProfilKemampuanBayar { get; set; }
        public string CAAnalisaCMO { get; set; }
        public string CAKesimpulanAnalisa { get; set; }
        public string KacabAlurProses { get; set; }
        public string KacabTekananApproval { get; set; }
        public string KacabKonflikKepentingan { get; set; }
        public string KacabProfilNasabah { get; set; }
        public string KacabProfilKebutuhanUnit { get; set; }
        public string KacabProfilKemampuanBayar { get; set; }
        public string KacabProfilCMO { get; set; }
        public string KacabProfilCA { get; set; }
        public string KacabKeseriusanAnalisaBM { get; set; }
        public string KacabKesimpulanAnalisa { get; set; }
        public DateTime tglSurvey { get; set; }
        public DateTime tglOrder { get; set; }
        public string CMOName { get; set; }
        public string CAname { get; set; }
        public DateTime TglKomiteCA { get; set; }
        public string KACABname { get; set; }
        public DateTime TglKomiteKACAB { get; set; }
    }
}